/* Generated by SquareLine Studio (https://squareline.io) */

#include "ui.h"

#ifndef UI_FONT_SEVENSEG
#define UI_FONT_SEVENSEG 1
#endif

#if UI_FONT_SEVENSEG

/*-----------------
 *    BITMAPS
 *----------------*/

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0030 "0" */
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff,

    /* U+0031 "1" */
    0xff, 0xff, 0xff, 0xff, 0xff,

    /* U+0032 "2" */
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,

    /* ... rest of glyphs omitted for brevity ... */
};

/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 256, .box_w = 16, .box_h = 32, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 64, .adv_w = 256, .box_w = 8, .box_h = 32, .ofs_x = 4, .ofs_y = 0},
    {.bitmap_index = 96, .adv_w = 256, .box_w = 16, .box_h = 32, .ofs_x = 0, .ofs_y = 0}
    /* ... */
};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 48, .range_length = 10, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }
};

/*-----------------
 *    KERNING
 *----------------*/

static const lv_font_fmt_txt_kern_pair_t kern_pairs = {
    .glyph_ids = NULL,
    .values = NULL,
    .pair_cnt = 0,
    .glyph_ids_size = 0
};

/*-----------------
 *  ALL CUSTOM DATA
 *----------------*/

static lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = &kern_pairs,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0
};

/*-----------------
 *  PUBLIC FONT
 *----------------*/

lv_font_t ui_font_sevenSeg = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 32,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .dsc = &font_dsc
};

#endif /*#if UI_FONT_SEVENSEG*/
